// <auto-generated />
using DotNET_Console_Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNET_Console_Application.Migrations
{
    [DbContext(typeof(ExerciseContext))]
    partial class ExerciseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DotNET_Console_Application.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_number");

                    b.HasKey("Id");

                    b.ToTable("classroom");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            RoomNumber = 1
                        },
                        new
                        {
                            Id = -2,
                            RoomNumber = 2
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("middle_name");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ClassId = -1,
                            FirstName = "John",
                            LastName = "Doe",
                            MiddleName = "Robert"
                        },
                        new
                        {
                            Id = -2,
                            ClassId = -2,
                            FirstName = "Jane",
                            LastName = "Doe",
                            MiddleName = "Joanne"
                        });
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Student", b =>
                {
                    b.HasOne("DotNET_Console_Application.Models.Classroom", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("DotNET_Console_Application.Models.Classroom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
